package com.devapps.droids.adapter;

import java.util.ArrayList;

import android.content.Context;
import android.content.Intent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

import com.devapps.droids.R;
import com.devapps.droids.models.HouseListingItem;
import com.devapps.droids.ui.LiveFeedActivity;
import com.devapps.droids.ui.LocalVideoActivity;
import com.devapps.droids.ui.PhotoSphereActivity;

/**
 * An adapter class for displaying the data inside the ListView. As as the bridge between the data & the UI.
 * 
 * Created by mahendraliya on 26/04/15.
 */
public class HouseListingArrayAdapter extends ArrayAdapter<HouseListingItem> {

	private final Context mContext;
	private final ArrayList<HouseListingItem> data;
	private Events events = null;

	/**
	 * 
	 * @param context The Context of the calling activity
	 * @param data The data to be used for displaying
	 */
	public HouseListingArrayAdapter(Context context, ArrayList<HouseListingItem> data) {
		super(context, R.layout.item_house_listing, data);
		this.mContext = context;
		this.data = data;
		this.events = new Events();
	}

	@Override
	public View getView(int position, View convertView, ViewGroup parent) {
		ViewHolder viewHolder;

		if (convertView == null) {
			convertView = ((LayoutInflater) mContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE)).inflate(R.layout.item_house_listing, parent, false);
			viewHolder = new ViewHolder();

			viewHolder.imgHouseSnap = (ImageView) convertView.findViewById(R.id.imgHouseSnap);
			viewHolder.lblHouseListingDisplayName = (TextView) convertView.findViewById(R.id.lblHouseListingDisplayName);
			viewHolder.imgView360 = (ImageView) convertView.findViewById(R.id.imgView360);
			viewHolder.imgViewBioscope = (ImageView) convertView.findViewById(R.id.imgViewBioscope);
			viewHolder.imgViewLiveFeed = (ImageView) convertView.findViewById(R.id.imgViewLiveFeed);
			
			convertView.setTag(viewHolder);
		} else {
			viewHolder = (ViewHolder) convertView.getTag();
		}

		// Use data.get(position).getImageURL() // Actual sceneria - show the URL
		viewHolder.imgHouseSnap.setImageDrawable(mContext.getResources().getDrawable(R.drawable.home_icon));
		viewHolder.lblHouseListingDisplayName.setText(data.get(position).getName());

		// Set the EventListeners again - as the data may be dynamic ???
		viewHolder.imgView360.setOnClickListener(events.click360Listener);
		viewHolder.imgViewBioscope.setOnClickListener(events.clickBioscopeListener);
		viewHolder.imgViewLiveFeed.setOnClickListener(events.clickLiveFeedListener);
		
		return convertView;
	}

	/**
	 * The Holder Pattern for the ListView and its underlying adapter.
	 * 
	 * @author mahendraliya
	 *
	 */
	private static class ViewHolder {
		TextView lblHouseListingDisplayName;
		ImageView imgHouseSnap;
		ImageView imgView360;
		ImageView imgViewBioscope;
		ImageView imgViewLiveFeed;
	}

	/**
	 * An event handler class for handling the click events generated by the individual item options.
	 * 
	 * @author mahendraliya
	 *
	 */
	private class Events {
		View.OnClickListener click360Listener = new View.OnClickListener() {

			@Override
			public void onClick(View v) {
				Intent photoSphereIntent = new Intent(mContext, PhotoSphereActivity.class);
				mContext.startActivity(photoSphereIntent);
			}
		};

		View.OnClickListener clickBioscopeListener = new View.OnClickListener() {

			@Override
			public void onClick(View v) {
				Intent photoSphereIntent = new Intent(mContext, LocalVideoActivity.class);
				mContext.startActivity(photoSphereIntent);
			}
		};

		View.OnClickListener clickLiveFeedListener = new View.OnClickListener() {

			@Override
			public void onClick(View v) {
				Intent photoSphereIntent = new Intent(mContext, LiveFeedActivity.class);
				mContext.startActivity(photoSphereIntent);
			}
		};
	}

}
